### ISSUE TITLE
stucked on login page of web ui

### ISSUE THREAD

**Issue by freakazoidz** [bettercap/ui#44] opened 2021-01-07 20:34 UTC
* Bettercap version 2.28
* OS version debian 5.7.6 architecture amd64
* Go version go1.15.6
* Caplet http-ui
* **Full debug output** 
```
[21:24:35] [sys.log] [dbg] FindGateway(wlan0) [cmd=ip opts=[route] parser=^(default|[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\svia\s([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)\sdev\s(\S+).*$]
[21:24:35] [sys.log] [dbg] FindGateway(wlan0) output:
default via 192.168.0.1 dev wlan0 proto dhcp metric 600 
192.168.0.0/24 dev wlan0 proto kernel scope link src 192.168.0.122 metric 600
[21:24:35] [mod.started] api.rest
[21:24:35] [sys.log] [dbg] gateway is 192.168.0.1[50:0f:f5:e3:b8:d0]
192.168.0.0/24 > 192.168.0.122  » [21:24:35] [mod.started] http.server
192.168.0.0/24 > 192.168.0.122  » [21:24:35] [mod.started] api.rest
192.168.0.0/24 > 192.168.0.122  » [21:24:35] [sys.log] [inf] http.server starting on http://127.0.0.1:80
192.168.0.0/24 > 192.168.0.122  » [21:24:35] [sys.log] [inf] api.rest api server starting on http://127.0.0.1:8081
192.168.0.0/24 > 192.168.0.122  » [21:24:35] [mod.started] http.server
192.168.0.0/24 > 192.168.0.122  » [21:24:35] [sys.log] [inf] http.server starting on http://127.0.0.1:80
192.168.0.0/24 > 192.168.0.122  » [21:24:50] [sys.log] [dbg] http.server 127.0.0.1 GET 127.0.0.1/
192.168.0.0/24 > 192.168.0.122  » [21:24:50] [sys.log] [dbg] http.server 127.0.0.1 GET 127.0.0.1/runtime.26209474bfa8dc87a77c.js
192.168.0.0/24 > 192.168.0.122  » [21:24:50] [sys.log] [dbg] http.server 127.0.0.1 GET 127.0.0.1/polyfills.681b44b3f292a3819611.js
192.168.0.0/24 > 192.168.0.122  » [21:24:50] [sys.log] [dbg] http.server 127.0.0.1 GET 127.0.0.1/main.ec83a59338123ba3bb5d.js
192.168.0.0/24 > 192.168.0.122  » [21:24:50] [sys.log] [dbg] http.server 127.0.0.1 GET 127.0.0.1/scripts.68228f7acaf48355d8cf.js
192.168.0.0/24 > 192.168.0.122  » [21:24:50] [sys.log] [dbg] http.server 127.0.0.1 GET 127.0.0.1/styles.92a454e3ed7c5bffbed3.css
192.168.0.0/24 > 192.168.0.122  » [21:24:50] [sys.log] [dbg] http.server 127.0.0.1 GET 127.0.0.1/assets/images/logo.png
192.168.0.0/24 > 192.168.0.122  »  
```

### Steps to Reproduce

1. launch web ui with : sudo bettercap -caplet http-ui
2. connect to 127.0.0.1 
3. enter credentials ( for testing user, pass)
4. click on "login" 

**Expected behavior:** 
after install the last realease of golang and bettercap , i wanted to try the bettercap's ui 

**Actual behavior:** 
i'm stuck on login page , nothing happened 

i hope give a complete report , thanks for your help 
and sorry for my bad english

**Comment by evilsocket** [comment] 2021-01-08 15:05
also, this seems a duplicate of #29, did you try to just install the ui via "ui.update" and clear the browser cache?

**Comment by freakazoidz** [comment] 2021-01-08 16:16
> i'm assuming you are using the latest version of both bettercap and the UI right?

yes , it's a fresh install, i followed the " compiling from sources" method for installation 



> also, this seems a duplicate of #29, did you try to just install the ui via "ui.update" and clear the browser cache?

i tried this a few minutes ago , no changes for me , i'll try to install the ui manually and if it's better or not

**Comment by evilsocket** [comment] 2021-01-08 16:20
those are not errors, don't worry about that

**Comment by evilsocket** [comment] 2021-01-08 16:21
once you installed bettercap, please install the ui by running:

    sudo bettercap -eval "ui.update; caplets.update; q"

and then just start it normally with:

    sudo bettercap -caplet http-ui

**Comment by freakazoidz** [comment] 2021-01-08 16:27
> sudo bettercap -eval "ui.update; caplets.update; q"

it's the method i use from the start

**Comment by evilsocket** [comment] 2021-01-08 16:28
good, just wanted to make sure, people use all sorts of unsupported ways XD

**Comment by freakazoidz** [comment] 2021-01-08 16:31
> good, just wanted to make sure, people use all sorts of unsupported ways XD

yeah i understand ^^ , i want it works , then i don't take any liberties ... in any case at the beginning xD

**Comment by freakazoidz** [comment] 2021-01-08 20:37
i tried to reinstall the ui manually , (like here : https://github.com/bettercap/ui/issues/29)
but no changes for me ... i don't know where to search for the moment

**Comment by evilsocket** [comment] 2021-01-08 20:53
ok i'll try to reproduce it in a vm when i have a moment

**Comment by freakazoidz** [comment] 2021-01-08 22:22
> ok i'll try to reproduce it in a vm when i have a moment

don't bother with that , i finally found the solution.

i give it for who want it : 

download the last version with : sudo wget https://github.com/bettercap/bettercap/releases/download/v2.28/bettercap_linux_amd64_v2.28.zip

remove the bettercap folder: 
sudo rm /usr/local/bin/bettercap 

copy bettercap on bin folder:
sudo cp bettercap_linux_amd64_v2.28.zip /usr/local/bin

unzip it : 
sudo unzip bettercap_linux_amd64_v2.28.zip

and if you don't do it install the ui : 
sudo bettercap -eval "ui.update; caplets.update; q"

and you can run it (my method can be optimized but it works like that ) 

thank you for taking time for me @evilsocket 

i hope help someone at my turn :)

**Comment by evilsocket** [comment] 2021-01-08 22:28
glad you worked it out! have fun

**Comment by curious-ninja** [comment] 2021-01-10 16:39
This issue seems to still exist.

This morning I built bettercap from the master branch and installed the ui via "ui.update".
And the login screen doesn't do anything after pressing the LOGIN button.

No errors in console. Just the following messages:
main.ec83a59338123ba3bb5d.js:1 found stored credentials
main.ec83a59338123ba3bb5d.js:1 api.login()
main.ec83a59338123ba3bb5d.js:1 env: {production: true, name: "ui", version: "1.3.0", requires: "2.24"}
/#/login?returnTo=%2Fevents:1 Autofocus processing was blocked because a document's URL has a fragment '#/login?returnTo=%2Fevents'.
main.ec83a59338123ba3bb5d.js:1 api.login()


Bettercap version: master branch, January 10th, 2020
OS version Kali Linux 2020.4 amd64
Go version: 1.15.6
Caplet: http-ui
UI Version: 1.3.0

I had a previously built version from around January 1st that worked ok.
So it's gotta be a recent commit. 
Bettercap Release v2.28 verified works ok.

**Comment by Cr4sh** [comment] 2021-01-12 13:59
Have exactly the same issue. I found out that it stucking at the login page because REST API is not responding to HTTP requests:
```
$ curl -v 127.0.0.1:8081
* Rebuilt URL to: 127.0.0.1:8081/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 405 Method Not Allowed
< Date: Tue, 12 Jan 2021 13:40:02 GMT
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact
```
```
$ curl -v 127.0.0.1:8081/api/session
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> GET /api/session HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.58.0
> Accept: */*
>

... nothing happens, it just waits for HTTP reply
```

**Comment by evilsocket** [comment] 2021-01-12 14:01
better test it with a browser and not with CURL

**Comment by Cr4sh** [comment] 2021-01-13 08:28
That's exactly how I started to investigate this issue.

**Comment by Wh1t3Fox** [comment] 2021-01-15 15:05
I'm experiencing the same issue with v2.28

Dev console in Firefox is throwing CORS errors.

![console](https://i.imgur.com/ubIHOR6.png)

![network](https://i.imgur.com/9bfTn14.png)

**Comment by evilsocket** [comment] 2021-01-15 15:07
what's the value of api.rest.alloworigin in bettercap?=

**Comment by Wh1t3Fox** [comment] 2021-01-15 15:12
value was set to: ``` api.rest.alloworigin: '*' ```

When I add ``` set api.rest.alloworigin: * ``` to the cap file, the CORS error goes away, but the hanging remains.

![console](https://i.imgur.com/qC2WqaG.png)
![network](https://i.imgur.com/bH70yhL.png)

**Comment by evilsocket** [comment] 2021-01-15 15:13
and what's the URL you're accessing the UI from?

**Comment by Wh1t3Fox** [comment] 2021-01-15 15:14
``` http://localhost ```

![screen](https://i.imgur.com/Q1JbMG8.png)

**Comment by evilsocket** [comment] 2021-01-15 15:15
that's super weird ... will try to replicate somehow, thanks for all the info guys

**Comment by Wh1t3Fox** [comment] 2021-01-15 15:16
it's very bizarre, hit me up if you need anything else

**Comment by curious-ninja** [comment] 2021-01-15 15:43
I believe this may be the same issue as:
https://github.com/bettercap/bettercap/issues/811

**Comment by evilsocket** [comment] 2021-01-15 15:44
nope

**Comment by evilsocket** [comment] 2021-01-15 16:50
oook, i've finally managed to replicate it on a clean ubuntu vm install and firefox ... now it's debugging time 🤞🏻

**Comment by evilsocket** [comment] 2021-01-15 16:55
actually @curious-ninja is right, this is a duplicate of https://github.com/bettercap/bettercap/issues/811 the UI is stuck because of a deadlock, closing this one and continuing the conv there guys.

**Closed by evilsocket** 2021-01-15 16:55 UTC
