### ISSUE TITLE
A module to manage bettercap's UI. Disabled in Kali: use apt install bettercap-ui to install and/or update ui.

### ISSUE THREAD

**Issue by lalit3011agarwal** [bettercap/ui#61] opened 2021-06-19 10:50 UTC
in bettercap v2.31.1
i got an error regarding bettercap ui, unable to set ui intall path and install it.
![image](https://user-images.githubusercontent.com/70253887/122639861-ef0e2000-d119-11eb-8b0a-9fa93393807d.png)

**Comment by buffermet** [comment] 2021-09-12 23:45
`ui.update` is a module so you need to do `ui.update on`

**Comment by buffermet** [comment] 2021-09-12 23:52
Duplicate of https://github.com/bettercap/ui/issues/35

**Closed by buffermet** 2021-09-12 23:52 UTC
